CXX      = g++
CXXFLAGS = --std=c++17 -Wall -Wextra
HEADERS  = tree234.h tree234.ipp
DEMO_BIN = demo.out
TEST_BIN = test.out

module: tree234_module.o

tree234_module_stub.cpp:
	printf '#include "tree234.h"\nnamespace Tree234Namespace { template class Tree234<int>; }\n' > tree234_module_stub.cpp

tree234_module.o: tree234_module_stub.cpp $(HEADERS)
	$(CXX) $(CXXFLAGS) -c tree234_module_stub.cpp -o tree234_module.o

$(DEMO_BIN): demo.cpp $(HEADERS)
	$(CXX) $(CXXFLAGS) demo.cpp -o $(DEMO_BIN)

run_demo: $(DEMO_BIN)
	./$(DEMO_BIN)

$(TEST_BIN): test.cpp $(HEADERS)
	$(CXX) $(CXXFLAGS) test.cpp -o $(TEST_BIN)

run_test: $(TEST_BIN)
	./$(TEST_BIN)

clean:
	rm -f $(DEMO_BIN) $(TEST_BIN) tree234_module.o tree234_module_stub.cpp log.txt

rebuild: clean module $(DEMO_BIN) $(TEST_BIN)

fix:
	clang-tidy demo.cpp test.cpp --checks='bugprone-*' --fix --fix-errors --header-filter='.*' -- $(CXXFLAGS)
	clang-format --style=chromium -i demo.cpp test.cpp $(HEADERS)
